name: Datadog Demo CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run app with Datadog tracer
        run: |
          DD_API_KEY=${{ secrets.DD_API_KEY }} \
          DD_SITE="datadoghq.com" \
          ddtrace-run python app.py
